trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Java 17
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

# Optional: confirm Java version
- script: java -version
  displayName: 'Check Java Version'

# Build with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'program6/pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
